# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.consilx.com:
  peer0.pfizer.com:
  peer1.pfizer.com:
  peer0.manipalhospital.org:
  peer1.manipalhospital.org:

networks:
  ctn:

services:

  orderer.consilx.com:
    container_name: orderer.consilx.com
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.consilx.com
    networks:
      - ctn

  peer0.pfizer.com:
    container_name: peer0.pfizer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.pfizer.com
    networks:
      - ctn

  peer1.pfizer.com:
    container_name: peer1.pfizer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.pfizer.com
    networks:
      - ctn

  peer0.manipalhospital.org:
    container_name: peer0.manipalhospital.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manipalhospital.org
    networks:
      - ctn

  peer1.manipalhospital.org:
    container_name: peer1.manipalhospital.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.manipalhospital.org
    networks:
      - ctn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.pfizer.org:7051
      - CORE_PEER_LOCALMSPID=PfizerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/pfizer.com/peers/peer0.pfizer.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/pfizer.com/peers/peer0.pfizer.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/pfizer.com/peers/peer0.pfizer.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/pfizer.com/users/Admin@pfizer.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        # - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.consilx.com
      - peer0.pfizer.com
      - peer1.pfizer.com
      - peer0.manipalhospital.org
      - peer1.manipalhospital.org
    networks:
      - ctn
