# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.consilx.com:
    container_name: orderer.consilx.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ConsilXMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/consilx.com/orderers/orderer.consilx.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/consilx.com/orderers/orderer.consilx.com/tls/:/var/hyperledger/orderer/tls
    - orderer.consilx.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.pfizer.com:
    container_name: peer0.pfizer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.pfizer.com
      - CORE_PEER_ADDRESS=peer0.pfizer.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.pfizer.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pfizer.com:7051
      - CORE_PEER_LOCALMSPID=PfizerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/peer0.pfizer.com/peers/peer0.pfizer.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/peer0.pfizer.com/peers/peer0.pfizer.com/tls:/etc/hyperledger/fabric/tls
        - peer0.pfizer.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.pfizer.com:
    container_name: peer1.pfizer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.pfizer.com
      - CORE_PEER_ADDRESS=peer1.pfizer.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pfizer.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pfizer.com:7051
      - CORE_PEER_LOCALMSPID=PfizerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/peer0.pfizer.com/peers/peer1.pfizer.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/peer0.pfizer.com/peers/peer1.pfizer.com/tls:/etc/hyperledger/fabric/tls
        - peer1.pfizer.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.manipalhospital.org:
    container_name: peer0.manipalhospital.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.manipalhospital.org
      - CORE_PEER_ADDRESS=peer0.manipalhospital.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manipalhospital.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.manipalhospital.org:7051
      - CORE_PEER_LOCALMSPID=ManipalHospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/manipalhospital.org/peers/peer0.manipalhospital.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/manipalhospital.org/peers/peer0.manipalhospital.org/tls:/etc/hyperledger/fabric/tls
        - peer0.manipalhospital.org:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.manipalhospital.org:
    container_name: peer1.manipalhospital.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.manipalhospital.org
      - CORE_PEER_ADDRESS=peer1.manipalhospital.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.manipalhospital.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manipalhospital.org:7051
      - CORE_PEER_LOCALMSPID=ManipalHospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/manipalhospital.org/peers/peer1.manipalhospital.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/manipalhospital.org/peers/peer1.manipalhospital.org/tls:/etc/hyperledger/fabric/tls
        - peer1.manipalhospital.org:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
